title: "My Foam Blog"
author: "Jesse Freeman"
email: "your-email@domain.com"
description: "A collection of notes turned into blog posts."
favicon: "./favicon.ico"

# Theme Setup
remote_theme: huangyz0918/moving  # ✅ Enables Moving theme on GitHub Pages

# Site URL Setup
baseurl: "/foam-template"  # ✅ Must match your repo name
url: "https://jessefreeman.github.io"

# Blog Settings
permalink: /:year-:month-:day/:title/  # Clean URLs
paginate: 5  # Enables pagination

# Moving Theme Customizations
moving:
  avatar_url: "https://i.loli.net/2019/08/26/JzCLhDWPEybZr2T.jpg"  # Customize this
  about_you: "A minimalist blog powered by Jekyll."
  date_format: "%b %d"  # Customize date format
  back_to: "Home"  # Customize the back button text

# Enable Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Ensure assets (CSS & images) are included
include:
  - assets
