title: "My Foam Blog"
description: "A collection of notes turned into blog posts."
remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme  # Required for GitHub Pages to use remote themes
  - jekyll-seo-tag       # Adds metadata for SEO
  - jekyll-sitemap       # Generates sitemap.xml
  - jekyll-feed          # Enables RSS feed for blog

show_downloads: false  # Hide "Download" button in the footer
google_analytics: ""  # Add your tracking ID if needed

collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

include:
  - assets  # Ensures custom CSS and images are accessible

permalink: pretty  # Clean URLs without .html
