title: "My Foam Blog"
description: "A collection of notes turned into blog posts."
remote_theme: chesterhow/tale  # ✅ Enables Tale theme

# Site URL for GitHub Pages
baseurl: "/foam-template"  # ✅ Must match your repo name
url: "https://jessefreeman.github.io"

# Blog settings
permalink: /:year-:month-:day/:title/  # Clean URLs
paginate: 5  # Enables pagination

# Enable required plugins
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Hide About page
navigation: []

# Enable Tags
collections:
  tags:
    output: true
