title: "My Foam Blog"
description: "A collection of notes turned into blog posts."
remote_theme: jekyll/minima

# Enable Jekyll's blog feature
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Base URL settings
baseurl: "/foam-template"  # Leave blank if deploying at repo root
url: "https://jessefreeman.github.io"

# Enable plugins for SEO and RSS
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Default front matter for blog posts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: "post"

# Image handling (optional)
defaults:
  - scope:
      path: "images"
    values:
      image: true

