title: "My Foam Blog"
description: "A collection of notes turned into blog posts."
remote_theme: chesterhow/tale  # ✅ Enables Tale theme

# Author
author:
  name:         Jesse Freeman
  url:          https://jessefreeman.com
  email:        jessefreeman@gmail.com

# Site URL for GitHub Pages
baseurl: "/foam-template"  # ✅ Must match your repo name
url: "https://jessefreeman.github.io"

# Blog settings
permalink: /:year-:month-:day/:title/  # Clean URLs
paginate: 5  # Enables pagination

# Enable required plugins
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Build settings
markdown:       kramdown
include:
  - _pages
