title: "My Foam Blog"
description: "A collection of notes turned into blog posts."
remote_theme: chesterhow/tale  # Using Tale as a remote theme

baseurl: "/foam-template"  # ✅ Important! Must match repo name
url: "https://jessefreeman.github.io"

permalink: /:year-:month-:day/:title  # Clean URLs
paginate: 5  # Enables pagination

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Optional: Disqus for comments
disqus: ""  # Add your Disqus ID if needed

show_downloads: false  # Removes "Download" button

include:
  - assets  # Ensures Jekyll loads CSS files
